AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Database Stack - Creates an RDS MySQL database, a subnet group, a security
  group, and a secret in Secrets Manager to hold the master credentials.

Parameters:
  Environment:
    Type: String
    Description: The environment name (e.g., Test, Acceptance, Production).
    AllowedValues: [Test, Acceptance, Production]

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID to deploy the database into.

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: The private subnets for the database.

  DBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The ID of the Security Group for the database.

Conditions:
  IsProduction: !Equals [!Ref Environment, Production]
  IsAcceptanceOrProduction: !Or [!Equals [!Ref Environment, Acceptance], !Condition IsProduction]

Mappings:
  DatabaseConfig:
    Test:
      InstanceClass: db.t3.micro
    Acceptance:
      InstanceClass: db.t3.small
    Production:
      InstanceClass: db.t3.medium # Upscale for Production

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'Subnet group for RDS'
      SubnetIds: !Ref PrivateSubnetIds

  # Secret for the database master user credentials
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub "Credentials for the ${Environment} To-Do App Database"
      Name: !Sub "${Environment}/TodoAppDB/credentials"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-DB-Credentials'

  # The RDS Database Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${Environment}-todo-app-db'
      Engine: mysql
      EngineVersion: '8.0'
      DBInstanceClass: !FindInMap [DatabaseConfig, !Ref Environment, InstanceClass]
      AllocatedStorage: '20'
      DBName: 'TodoAppDB'
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:username}}']]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DBSecret, ':SecretString:password}}']]
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroupId
      PubliclyAccessible: false
      # Environment-specific settings
      MultiAZ: !If [IsAcceptanceOrProduction, true, false] # HA for Acceptance and Production
      StorageEncrypted: !If [IsProduction, true, false] # Encryption for Production
      DeletionProtection: !If [IsProduction, true, false] # Protection for Production
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-DBInstance'

Outputs:
  DBEndpoint:
    Description: The connection endpoint of the RDS instance.
    Value: !GetAtt DBInstance.Endpoint.Address
  DBSecretArn:
    Description: The ARN of the secret holding the database credentials.
    Value: !Ref DBSecret