AWSTemplateFormatVersion: '2010-09-09'
Description: Main CloudFormation template for deploying the multi-tier ECS application.

Parameters:
  Environment:
    Description: The environment to deploy to (e.g., Test, Acceptance, Production).
    Type: String
    AllowedValues:
      - Test
      - Acceptance
      - Production
    Default: Test

  ImageTag:
    Description: The tag for the Docker images to deploy (e.g., the git commit SHA).
    Type: String

  ApplicationLayerECRRepositoryUri:
    Description: The URI of the pre-existing Application Layer ECR repository.
    Type: String

  WebLayerECRRepositoryUri:
    Description: The URI of the pre-existing Web Layer ECR repository.
    Type: String
  LabRoleArn:
    Description: The ARN of the IAM role for the ECS tasks.
    Type: String
  
  # Parameters for Bastion Host (Production only)
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the bastion host.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  
  BastionAllowedCIDR:
    Description: The IP address range that can be used to SSH to the EC2 instances.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.

Conditions:
  IsProduction: !Equals [!Ref Environment, Production]
    
Resources:
  DBNameSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${Environment}/TodoAppDB/dbname'
      Type: String
      Value: 'TodoAppDB'
      Description: !Sub 'Database name for the ${Environment} To-Do App Database'
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network.yaml
      Parameters:
        Environment: !Ref Environment

  EcsClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecs-cluster.yaml
      Parameters:
        Environment: !Ref Environment

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt NetworkStack.Outputs.PublicSubnetIds # Pass Public Subnets
        KeyName: !Ref KeyName # Pass KeyName
        BastionAllowedCIDR: !Ref BastionAllowedCIDR # Pass Allowed CIDR

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./database.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
        DBSecurityGroupId: !GetAtt SecurityStack.Outputs.DBSecurityGroupId

  ApplicationServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./application-service.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
        EcsClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        ApplicationLayerECRRepositoryUri: !Ref ApplicationLayerECRRepositoryUri
        ImageTag: !Ref ImageTag
        DBEndpoint: !GetAtt DatabaseStack.Outputs.DBEndpoint
        DBSecretArn: !GetAtt DatabaseStack.Outputs.DBSecretArn
        ApplicationServiceSGId: !GetAtt SecurityStack.Outputs.ApplicationServiceSGId
        InternalAlbSGId: !GetAtt SecurityStack.Outputs.InternalAlbSGId
        LabRoleArn: !Ref LabRoleArn

  WebServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ApplicationServiceStack # Ensure backend is ready before frontend
    Properties:
      TemplateURL: ./web-service.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt NetworkStack.Outputs.PublicSubnetIds
        PrivateSubnetIds: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
        EcsClusterName: !GetAtt EcsClusterStack.Outputs.ClusterName
        WebLayerECRRepositoryUri: !Ref WebLayerECRRepositoryUri
        ImageTag: !Ref ImageTag
        BackendApiUrl: !GetAtt ApplicationServiceStack.Outputs.InternalALBDnsName
        AlbSecurityGroupId: !GetAtt SecurityStack.Outputs.AlbSecurityGroupId
        WebServiceSecurityGroupId: !GetAtt SecurityStack.Outputs.WebServiceSecurityGroupId
        LabRoleArn: !Ref LabRoleArn


Outputs:
  WebAppURL:
    Description: "URL for the deployed web application"
    Value: !GetAtt WebServiceStack.Outputs.WebAppURL
  DBNameParameterName:
    Description: "The name of the SSM parameter that stores the database name"
    Value: !Ref DBNameSSMParameter
  BastionPublicIP:
    Description: "Public IP address of the Bastion Host (for Production environment)"
    Value: !If
      - IsProduction
      - !GetAtt SecurityStack.Outputs.BastionPublicIP
      - '' # Return an empty string if not Production